// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Participant struct {
	ID    int32
	Game1 pgtype.Int4
	Game2 pgtype.Int4
	Game3 pgtype.Int4
	Name  string
}
