// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CompletedQuestion struct {
	ID             int32
	TeamID         pgtype.Text
	QuestionStatus pgtype.Text
	CompletedAt    pgtype.Timestamptz
}

type Team struct {
	TeamID       string
	TeamName     string
	PasswordHash string
}

type TeamPoint struct {
	TeamID      string
	TotalPoints pgtype.Int4
}
