// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
)

const listMembers = `-- name: ListMembers :many
SELECT 
    RANK() OVER (ORDER BY (COALESCE(game1, 0) + COALESCE(game2, 0) + COALESCE(game3, 0)) DESC) AS rank,
    name, 
    COALESCE(game1, 0) + COALESCE(game2, 0) + COALESCE(game3, 0) AS scores
FROM participants
`

type ListMembersRow struct {
	Rank   int64
	Name   string
	Scores int32
}

func (q *Queries) ListMembers(ctx context.Context) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(&i.Rank, &i.Name, &i.Scores); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
