name: Build and Push Image

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '!assets/**'
      - '!env.example'
      - '!README.md'
      - '!sqlc/**'
      - '!.github/workflows/goreleaser.yml'

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
    
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/sourasishbasu/leaderboard:latest

      - name: Log out from Docker Hub
        run: docker logout
