name: goreleaser
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '!assets/**'
      - '!env.example'
      - '!README.md'
      - '!sqlc/**'
      - '!.github/workflows/ci.yml'

permissions:
  contents: write
jobs:
  goreleaser:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}